# OpenSRF / Evergreen Ansible Installer Playbook
# Author: Bill Erickson <berickxx@gmail.com>

- hosts: '{{hosts}}'
  connection: local
  # Every command not explicitly run by opensrf/postgres requires root.  
  remote_user: root
  become_method: sudo
  vars_files:
    - settings.yml
  tasks:
  - name: Process OpenSRF Tasks
    include: opensrf/main.yml
  - name: Process Evergreen Tasks
    include: evergreen/main.yml
  - name: Process Optional Packages
    include: extras/main.yml
  - block:
    - name: Starting Services
      become: true
      become_user: opensrf
      environment:
        PATH: "{{ansible_env.PATH}}:{{eg_install_path}}/bin"
      shell: osrf_control --localhost --restart-all
    - name: Giving Services Time To Start...
      pause: seconds=10
    - name: Running Autogen
      become: true
      become_user: opensrf
      environment:
        PATH: "{{ansible_env.PATH}}:{{eg_install_path}}/bin"
      shell: autogen.sh
    - name: Reloading Apache
      service: name=apache2 state=reloaded
    when: start_services
