# OpenSRF / Evergreen Ansible Installer Playbook
# Author: Bill Erickson <berickxx@gmail.com>

- hosts: '{{hosts}}'
  remote_user: '{{deploy_user}}'
  become_method: sudo
  vars_files:
    - settings.yml
  tasks:
  - name: Process Database
    include: postgres/main.yml
