- name: Install OpenSRF Service File
  become: true
  template: 
    src: extras/service-files/opensrf.service.j2
    dest: /lib/systemd/system/opensrf.service 
    owner: root
    group: root
    mode: 0644
  when: use_service_opensrf | bool
- name: Install Evergreen Reporter Service File
  become: true
  template: 
    src: extras/service-files/evergreen-reporter.service.j2
    dest: /lib/systemd/system/evergreen-reporter.service 
    owner: root
    group: root
    mode: 0644
  when: use_service_reporter | bool
- name: Reload Systemd Configs
  systemd:
    daemon_reload: true
- name: Enable OpenSRF Service
  systemd:
    name: opensrf
    enabled: true
  when: use_service_opensrf | bool
