- name: Install OpenSRF Router Service File
  become: true
  template: 
    src: extras/service-files/opensrf-router.service.j2
    dest: /lib/systemd/system/opensrf-router.service 
    owner: root
    group: root
    mode: 0644
- name: Install OpenSRF Service File
  become: true
  template: 
    src: extras/service-files/opensrf.service.j2
    dest: /lib/systemd/system/opensrf.service 
    owner: root
    group: root
    mode: 0644
  when: use_service_opensrf | bool
- name: Install OpenSRF Websockets Service File
  become: true
  template: 
    src: extras/service-files/opensrf-websockets.service.j2
    dest: /lib/systemd/system/opensrf-websockets.service
    owner: root
    group: root
    mode: 0644
- name: Install Evergreen Reporter Service File
  become: true
  template: 
    src: extras/service-files/evergreen-reporter.service.j2
    dest: /lib/systemd/system/evergreen-reporter.service 
    owner: root
    group: root
    mode: 0644
  when: use_service_reporter | bool
- name: Reload Systemd Configs
  systemd:
    daemon_reload: true
- name: Enable OpenSRF Service
  systemd:
    name: opensrf
    enabled: true
  when: use_service_opensrf | bool
- name: Enable OpenSRF Websockets Service
  systemd:
    name: opensrf-websockets
    enabled: true
- name: Enable Evergreen Reporter Service
  systemd:
    name: evergreen-reporter
    enabled: true
  when: use_service_reporter | bool

